In [1]:
import pandas as pd
import numpy as np

In [2]:
file_path = 'pmi_ejercicio.xlsx'
df_PMI = pd.read_excel(file_path)

In [3]:
df_PMI.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   Unnamed: 0  4 non-null      object
 1   Unnamed: 1  5 non-null      object
 2   Unnamed: 2  5 non-null      object
 3   Unnamed: 3  5 non-null      object
 4   Unnamed: 4  5 non-null      object
 5   Unnamed: 5  5 non-null      object
dtypes: object(6)
memory usage: 368.0+ bytes


In [4]:
df_PMI.describe()

Unnamed: 0 Unnamed: 1 Unnamed: 2 Unnamed: 3  Unnamed: 4 Unnamed: 5
count           4          5          5          5           5          5
unique          4          5          5          5           4          5
top        Cherry   Computer       data     result           5      sugar
freq            1          1          1          1           2          1

In [5]:
df_PMI.head()

Unnamed: 0 Unnamed: 1 Unnamed: 2 Unnamed: 3 Unnamed: 4 Unnamed: 5
0          NaN   Computer       data     result        pie      sugar
1       Cherry          2          8          9      44260         25
2   Strawberry          0          0          1          5         19
3      Digital       1670       1683         85          5          4
4  Information       3325       3982        378        512         13

In [6]:
# Limpia de datos
df_PMI_new = df_PMI.dropna(how='all', axis=1).dropna(how='all', axis=0)
df_PMI_new.columns = df_PMI_new.iloc[0]  
df_PMI_new = df_PMI_new.drop(0)  

df_PMI_new = df_PMI_new.apply(pd.to_numeric, errors='ignore')
df_PMI_new.reset_index(drop=True, inplace=True)

df_PMI.head()

Unnamed: 0 Unnamed: 1 Unnamed: 2 Unnamed: 3 Unnamed: 4 Unnamed: 5
0          NaN   Computer       data     result        pie      sugar
1       Cherry          2          8          9      44260         25
2   Strawberry          0          0          1          5         19
3      Digital       1670       1683         85          5          4
4  Information       3325       3982        378        512         13

In [7]:
def PalphaR(matrix, alpha=1.0):
    row_totals = matrix.sum(axis=1)
    V = matrix.shape[1]

    P_alpha = (matrix + alpha) / (row_totals[:, np.newaxis] + alpha * V)
    
    return P_alpha

def PPMI(matrix):
    row_totals = matrix.sum(axis=1)
    col_totals = matrix.sum(axis=0)
    total_count = matrix.sum().sum()
    
    Pxy = matrix / total_count
    Px = row_totals / total_count
    Py = col_totals / total_count
    
    PPMI = np.maximum(np.log2(Pxy / (Px[:, np.newaxis] * Py[np.newaxis, :])), 0)
    
    return PPMI

matrix = df_PMI_new.iloc[:, 1:].astype(float).values

PalphaRes = PalphaR(matrix, alpha=1.0)
PPMIRes = PPMI(matrix)

/var/folders/8f/4tqfct110qxbk9qrh28g1lpr0000gn/T/ipykernel_10955/139225292.py:18: RuntimeWarning: divide by zero encountered in log2
  PPMI = np.maximum(np.log2(Pxy / (Px[:, np.newaxis] * Py[np.newaxis, :])), 0)


In [8]:
print(f"Resultados P_alpha: \n\n {PalphaRes}")

Resultados P_alpha: 

 [[6.77063351e-05 2.03119005e-04 2.25687784e-04 9.98916699e-01
  5.86788237e-04]
 [3.33333333e-02 3.33333333e-02 6.66666667e-02 2.00000000e-01
  6.66666667e-01]
 [4.84067207e-01 4.87833140e-01 2.49130939e-02 1.73812283e-03
  1.44843569e-03]
 [4.04869142e-01 4.84844796e-01 4.61351187e-02 6.24467438e-02
  1.70419963e-03]]


In [9]:
print(f"Resultados PPMI: \n\n {PPMIRes}")

Resultados PPMI: 

 [[0.         0.         0.         0.32071364 0.        ]
 [0.         0.         2.24322592 0.         9.44611247]
 [2.44043879 2.26857622 1.54534747 0.         0.09091557]
 [2.1819041  2.25899334 2.44615803 0.         0.53931436]]


In [10]:
P_alpha_df = pd.DataFrame(PalphaRes, index=df_PMI_new.iloc[:, 0], columns=df_PMI_new.columns[1:])
PPMI_df = pd.DataFrame(PPMIRes, index=df_PMI_new.iloc[:, 0], columns=df_PMI_new.columns[1:])

In [11]:
print("Resultados P_alpha: ")
P_alpha_df.head()

Resultados P_alpha: 


0            Computer      data    result       pie     sugar
nan                                                          
Cherry       0.000068  0.000203  0.000226  0.998917  0.000587
Strawberry   0.033333  0.033333  0.066667  0.200000  0.666667
Digital      0.484067  0.487833  0.024913  0.001738  0.001448
Information  0.404869  0.484845  0.046135  0.062447  0.001704

In [12]:
print("Resultados PPMI: ")
PPMI_df.head()

Resultados PPMI: 


0            Computer      data    result       pie     sugar
nan                                                          
Cherry       0.000000  0.000000  0.000000  0.320714  0.000000
Strawberry   0.000000  0.000000  2.243226  0.000000  9.446112
Digital      2.440439  2.268576  1.545347  0.000000  0.090916
Information  2.181904  2.258993  2.446158  0.000000  0.539314

In [13]:
print(df_PMI_new.iloc[:, 0])  
print(df_PMI_new.columns[1:]) 

0         Cherry
1     Strawberry
2        Digital
3    Information
Name: nan, dtype: object
Index(['Computer', 'data', 'result', 'pie', 'sugar'], dtype='object', name=0)


In [14]:
df_PMI_new = df_PMI_new.dropna(axis=0, how='any')  
df_PMI_new = df_PMI_new.dropna(axis=1, how='any')  
